### ISSUE TITLE
Inconsistencies when using with themes

### ISSUE THREAD

**Issue by verdonv** [AyeCode/wp-easy-updates#5]
Hi,

I am experiencing several inconsistencies when trying to use this with themes. I'll attempt to list them, and provide some screenshots below. The common symptom with all the inconsistent behaviour is that checking for available updates once will show that there are updates available. Refreshing and checking again for updates will show that there are none available. Going directly to the 'info' panel for a theme (with a known update) will expose different issue.

I haven't actually tried doing an update yet. Would like to sort these things out first.

These things exhibit slightly differently depending on whether I am testing with a stand-alone install, a multisite install, or even when I am checking using Infinite Wordpress. My gut tells me that the core problem (exhibited in the theme's info panel) is that it is looking for a license key for the theme, even though I have not added any license meta data in the themes style.css file.

![screen shot 2018-05-30 at 3 44 00 pm](https://user-images.githubusercontent.com/5149763/40783731-646ba8d2-64b1-11e8-9c85-a410f55027c2.png)

![screen shot 2018-05-30 at 3 42 36 pm](https://user-images.githubusercontent.com/5149763/40784294-3e154c36-64b3-11e8-8816-4c38db54903d.png)

![screen shot 2018-05-30 at 3 40 24 pm](https://user-images.githubusercontent.com/5149763/40784317-5550fa1c-64b3-11e8-9d1e-e3a44eee9e6f.png)

![screen shot 2018-05-30 at 3 40 46 pm](https://user-images.githubusercontent.com/5149763/40784327-5dba8baa-64b3-11e8-9f9b-c98f6e69cb20.png)

**Comment by verdonv** [comment]
I was able to successfully apply an update to a theme via Infinite Wordpress. I'm finding it awkward via normal means in a multisite, as it keeps disappearing from the available updates screen. Admittedly haven't been able to play much today.

**Comment by Stiofan** [comment]
Hello,

I have fixed the licence input if not required, however i can't replicate the updates showing/not showing.
I have never used "Infinite Wordpress" so i'm not sure if that is affecting things or if maybe you were testing after JUST updating a theme? (where sometimes the github cache can cause problems)

**Comment by verdonv** [comment]
The updates showing/not showing was happening for me in single standard installs, multi-site installs, and when using "Infinite Wordpress". I don't think it had anything to do with "Infinite Wordpress" but suspect it had to do with the licence input. In the end, "Infinite Wordpress" was the only way I was able to actually get the update done... so long as I didn't refresh :-) Regardless of how I was attempting to check for updates, some form of caching was at play. For instance, I would check for updates and it would show one available. I would reload the page and the update notice would go away. It would not come back for some time, no mater how many times and ways I attempted to refresh. Thenrandomly several hours later, the update would show again.

I'll kick the tires on this new version either this afternoon or Monday morning, and let you know ASAP. If I continue to see any weirdness, I can easily give you access to one of my installs if you want to muck about.

Thanks for your ongoing support of this plugin!

**Comment by Stiofan** [comment]
Sure, sounds good.  I tested on single and MU but could not replicate.
Talk soon.

**Comment by verdonv** [comment]
Hi,

Sorry to be silent... was on a mini-holiday and am trying to catch up. I was able to update themes in a couple ways with this recent update. I'm still experiencing a little weirdness that seems caching related somewhere along the line. For instance, it took me 3 tries to get the Easy-Update plugin itself to update, and then when I back-versioned an installed theme for testing, it wouldn't show available update until the next morning, no matter how I tried to trigger a manual check.

I realize these comments are all anecdotal though :-) If you like, close this issue report as resolved, and over the next couple days I'll try to set up some more controlled testing to see if I can trigger anything weird. Even with the odd thing like this, this plugin is still a big help!

ttyl,
v

**Comment by Stiofan** [comment]
The issue for WPUE not updating is likely because github rate limits the API requests, if you were loading the updates screen over and over it might have used up your limit for the hour. 

I'm closing this, if you have any more issue please open a new topic.

Thanks,

Stiofan
